#!/usr/bin/env bash
#
# export_sources.sh — 把项目里的源码文件汇总成一个 Markdown。
#
# 用途：复制/分享项目时，一个文件即可阅读全部源码（相对路径 + 代码内容）。
#
# 用法:
#   ./scripts/export_sources.sh                 # 输出到 PROJECT_SOURCES.md
#   ./scripts/export_sources.sh out.md          # 输出到 out.md

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

OUTPUT="${1:-PROJECT_SOURCES.md}"

if ! command -v rg >/dev/null 2>&1; then
	echo "error: this script needs rg to collect source files" >&2
	exit 1
fi

EXCLUDE_GLOBS=(
	-g "!$OUTPUT"
	-g "!PROJECT_SOURCES.md"
	-g "!**/.git/**"
	-g "!**/.venv/**"
	-g "!**/.uv-cache/**"
	-g "!**/.ruff_cache/**"
	-g "!**/.pytest_cache/**"
	-g "!**/.ty/**"
	-g "!**/__pycache__/**"
	-g "!**/*.pyc"
	-g "!**/*.pyo"
	-g "!**/*-lock.yaml"
	-g "!**/pnpm-lock.yaml"
	-g "!**/package-lock.json"
	-g "!**/yarn.lock"
	-g "!**/uv.lock"
	-g "!**/poetry.lock"
	# ArcOfMarket 采集数据/密钥不进源码导出(避免把 5MB+ JSON 和 FRED key 塞进 md)
	-g "!**/data/**"
	-g "!**/.env"
	-g "!**/.env.local"
	-g "!**/.env.*.local"
	-g "!**/*.egg-info/**"
	-g "!**/.coverage"
	-g "!**/.build/**"
	-g "!**/.swiftpm/**"
	-g "!**/DerivedData/**"
	-g "!**/.playwright-cli/**"
	-g "!**/node_modules/**"
	-g "!**/dist/**"
	-g "!**/.npm-cache/**"
	-g "!script/**"
	-g "!output/**"
	-g "!**/qa-*.png"
	-g "!**/.DS_Store"
	-g "!docs/screener-sync-change.md"
)

is_text() {
	case "$1" in
	*.png | *.jpg | *.jpeg | *.gif | *.ico | *.pdf | *.zip | *.gz | *.parquet)
		return 1
		;;
	esac
	return 0
}

lang_for() {
	case "$1" in
	*.swift) echo swift ;;
	*.py) echo python ;;
	*.sh) echo bash ;;
	*.js | *.jsx) echo javascript ;;
	*.mjs) echo javascript ;;
	*.css) echo css ;;
	*.html) echo html ;;
	*.sql) echo sql ;;
	*.json) echo json ;;
	*.toml) echo toml ;;
	*.yml | *.yaml) echo yaml ;;
	*.md) echo markdown ;;
	*.cfg | *.ini) echo ini ;;
	*) echo "" ;;
	esac
}

# 用 while+数组读取，兼容 macOS 自带的 bash 3.2（没有 mapfile）。
FILES=()
while IFS= read -r f; do
	FILES+=("$f")
done < <(
	rg --files --hidden "${EXCLUDE_GLOBS[@]}" |
		while IFS= read -r f; do
			[[ -f "$f" ]] && echo "$f"
		done |
		sort
)

{
	echo "# Project Sources"
	echo
	echo "Generated by \`scripts/export_sources.sh\`. Each section is one file:"
	echo "its repo-relative path followed by its full contents."
	echo
	echo "Total files: ${#FILES[@]}"
	echo
	echo "## Table of Contents"
	echo
	for f in "${FILES[@]}"; do
		echo "- \`$f\`"
	done
	echo

	last_index=$((${#FILES[@]} - 1))
	for index in "${!FILES[@]}"; do
		f="${FILES[$index]}"
		echo "---"
		echo
		echo "## \`$f\`"
		echo
		if is_text "$f"; then
			lang="$(lang_for "$f")"
			echo "\`\`\`\`${lang}"
			cat "$f"
			# 保证代码块前有换行收尾，避免最后一行和 ``` 粘连。
			[[ -n "$(tail -c1 "$f")" ]] && echo
			echo "\`\`\`\`"
		else
			echo "_(binary or non-text file, contents omitted)_"
		fi
		if ((index < last_index)); then
			echo
		fi
	done
} >"$OUTPUT"

echo "wrote $OUTPUT (${#FILES[@]} files)"
