#!/usr/bin/env bash

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

OUTPUT="${1:-PROJECT_SOURCES.md}"

if ! command -v rg >/dev/null 2>&1; then
	echo "error: this script requires rg" >&2
	exit 1
fi

EXCLUDE_GLOBS=(
	-g "!$OUTPUT"
	-g "!PROJECT_SOURCES.md"
	-g "!project-export/**"
	-g "!**/.git/**"
	-g "!**/.evo/**"
	-g "!**/.venv/**"
	-g "!**/.pytest_cache/**"
	-g "!**/.ruff_cache/**"
	-g "!**/.playwright-cli/**"
	-g "!**/__pycache__/**"
	-g "!**/node_modules/**"
	-g "!**/outputs/**"
	-g "!**/dist/**"
	-g "!**/.research-store/**"
	-g "!**/.env"
	-g "!**/.env.*"
	-g "!**/*.pyc"
	-g "!**/*.sqlite"
	-g "!**/*.sqlite-*"
	-g "!**/*.db"
	-g "!**/*.db-shm"
	-g "!**/*.db-wal"
	-g "!**/*.png"
	-g "!**/*.jpg"
	-g "!**/*.jpeg"
	-g "!**/*.gif"
	-g "!**/*.ico"
	-g "!**/*.pdf"
	-g "!**/*.zip"
	-g "!**/*.gz"
	-g "!**/*.xlsx"
	-g "!**/*.parquet"
	-g "!**/.DS_Store"
)

lang_for() {
	case "$1" in
	*.py) echo python ;;
	*.toml) echo toml ;;
	*.json | *.jsonc | *.jsonl) echo json ;;
	*.yml | *.yaml) echo yaml ;;
	*.md) echo markdown ;;
	*.sh) echo bash ;;
	*) echo "" ;;
	esac
}

FILES=()
while IFS= read -r file; do
	FILES+=("$file")
done < <(rg --files --hidden "${EXCLUDE_GLOBS[@]}" | sort)

{
	echo "# ArcOfMarket Data Project Sources"
	echo
	echo "Generated by \`scripts/export_sources.sh\`. Each section contains one complete"
	echo "repo-relative text file. Secrets, local state, dependencies, caches," \
		"and binaries are excluded."
	echo
	echo "Restore with: \`bash restore_project.sh PROJECT_SOURCES.md <empty-target-directory>\`"
	echo
	echo "Total files: ${#FILES[@]}"
	echo
	echo "## Table of Contents"
	echo
	for file in "${FILES[@]}"; do
		echo "- \`$file\`"
	done
	echo

	for file in "${FILES[@]}"; do
		echo "---"
		echo
		echo "## \`$file\`"
		echo
		language="$(lang_for "$file")"
		echo "\`\`\`\`${language}"
		cat "$file"
		[[ -n "$(tail -c1 "$file")" ]] && echo
		echo "\`\`\`\`"
		echo
	done
} >"$OUTPUT"

echo "wrote $OUTPUT (${#FILES[@]} files)"
