#!/usr/bin/env python3
"""ArcOfMarket · 数据收割管线(harvest)

拉取外部数据 → 计算研究指标 → 写出 data/*.json(前端只读静态文件)。

数据源:
- 价格/指数/个股: yfinance；指数为价格回报，ETF/个股为 auto-adjusted 回报
- VIX 全家族 / SKEW: Cboe 官方历史 CSV
- 宏观: FRED 官方 API
- 金融压力: 美国财政部金融研究办公室 OFR FSI
- 成分股: Wikipedia

信任层在 audit.py / chain.py；本脚本只管拉取、计算和写出。
单个步骤失败时保留上一版文件，并把失败记录到 meta.json。
"""

import argparse
import hashlib
import json
import os
import re
import time
from collections.abc import Callable, Sequence
from datetime import UTC, datetime, timedelta
from io import StringIO
from pathlib import Path
from typing import Any, cast

import pandas as pd
import requests
import yfinance as yf

from scripts.dataset_rights import dataset_record
from scripts.index_statistics import (
    annual_performance,
    annual_return_distribution,
    drawdown_history,
    extreme_day_summary,
    holding_period_summary,
    intrayear_performance,
    market_cycles,
    monthly_seasonality,
    rolling_cagr_payload,
    rolling_five_year_performance,
    volatility_history,
)
from scripts.macro_indicators import equity_allocation_payload, equity_allocation_share
from scripts.pipeline_runtime import CallResult

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DATA.mkdir(exist_ok=True)


def load_local_env(path: Path = ROOT / ".env") -> None:
    """加载简单的 KEY=value 本地配置，不覆盖调用方已设置的环境变量。"""
    if not path.exists():
        return
    parsed = parse_env_values(path.read_text(encoding="utf-8"))
    os.environ.update({key: value for key, value in parsed.items() if key not in os.environ})


def parse_env_values(text: str) -> dict[str, str]:
    values = {}
    for candidate in text.splitlines():
        line = candidate.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, raw_value = line.split("=", 1)
        normalized_key = key.strip()
        if normalized_key:
            values[normalized_key] = raw_value.strip().strip("\"'")
    return values


load_local_env()

UA = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36"
    )
}

# 编排/衍生/溯源径归 ArcOfMarket(代码: PolyForm Noncommercial;指标: 单独可授权);
# 原始数值是各源发布的事实,归属各源。
LICENSE_TAG = (
    "Generated by ArcOfMarket; code and derived-metric rights are governed by "
    "LICENSE and THIRD_PARTY_NOTICES.md. "
    "Underlying values are facts transcribed from public sources "
    "(Yahoo Finance, Cboe, FRED, OFR, SEC, CFTC, NBER, and Wikipedia) "
    "and remain subject to those sources' own terms — no ownership claimed over them."
)
WIKIPEDIA_LICENSE_TAG = (
    "S&P 500 constituent-change table adapted from Wikipedia contributors, "
    "'List of S&P 500 companies', under CC BY-SA 4.0. ArcOfMarket normalized "
    "dates, fields, and citation markers. Source revision and license links are "
    "included in this dataset."
)


def pin(name: str, obj, license_tag: str = LICENSE_TAG) -> None:
    """写 data/*.json，并注入许可证与生成溯源信息。"""
    destination = DATA / name
    payload = obj
    if isinstance(payload, dict):
        rights = dataset_record(name)
        payload = {
            "_license": license_tag,
            "_provenance": {
                "schema_version": 1,
                "generated_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
                "generator": "scripts.harvest",
                "dataset_group": rights["group"],
                "source_ids": rights["source_ids"],
                "rights": {
                    "access": rights["access"],
                    "derived_output": rights["derived_output"],
                    "status": rights["status"],
                },
            },
            **{
                key: value
                for key, value in payload.items()
                if key not in {"_license", "_provenance"}
            },
        }
    serialized = json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + "\n"
    temporary = destination.with_name(f".{destination.name}.tmp")
    temporary.write_text(serialized, encoding="utf-8")
    temporary.replace(destination)
    print(f"  pinned {name} ({destination.stat().st_size / 1024:.0f} KB)")


_FAILURES: list[dict] = []
OPTIONAL_SOURCES = {"forward_pe", "insider", "thirteenf"}


def run_section(
    label: str,
    operation: Callable[..., Any],
    *args: Any,
    blocking: bool = True,
    **kwargs: Any,
) -> bool:
    """Run one pipeline step and record a structured failure when it cannot finish."""
    result = CallResult.invoke(operation, *args, **kwargs)
    if result.succeeded:
        return True
    error = result.error or RuntimeError("pipeline step failed without an error")
    failure = {
        "section": label,
        "error": f"{type(error).__name__}: {str(error)[:200]}",
        "blocking": blocking,
    }
    _FAILURES.append(failure)
    print(f"  ⚠️ {label} 失败（保留上一版文件）: {failure['error']}")
    return False


def normalized_timestamp(value: Any) -> pd.Timestamp:
    """把 pandas 可识别日期转为无时区的日粒度 Timestamp。"""
    timestamp = cast(pd.Timestamp, pd.Timestamp(value))
    naive = timestamp.tz_localize(None)
    return naive.normalize()


def fetch_history(
    ticker: str,
    retries: int = 4,
    expected_date: pd.Timestamp | None = None,
) -> pd.DataFrame:
    """yfinance 历史价。BRK.B 用连字符、欧股 MC.PA 保留点：原样优先、连字符兜底。
    让 yfinance 管理 curl_cffi 会话、cookie 与 crumb；失败时指数退避。"""
    candidates = [ticker] + ([ticker.replace(".", "-")] if "." in ticker else [])
    for i in range(retries):
        for sym in candidates:
            try:
                # 不传 requests.Session：它没有浏览器 TLS/HTTP2 指纹，会被 Yahoo 直接限流。
                t = yf.Ticker(sym)
                df = t.history(period="max", auto_adjust=True)
                repaired_date = None
                incomplete_latest = (
                    "Close" in df.columns and not df.empty and pd.isna(df["Close"].iloc[-1])
                )
                latest_date = normalized_timestamp(df.index[-1]) if not df.empty else None
                lagging_latest = (
                    expected_date is not None
                    and latest_date is not None
                    and latest_date < normalized_timestamp(expected_date)
                )
                was_incomplete = incomplete_latest
                was_lagging = lagging_latest
                if incomplete_latest or lagging_latest:
                    try:
                        repair = t.history(
                            period="10d",
                            auto_adjust=True,
                            repair=True,
                            keepna=True,
                        )
                        repair = repair.drop(columns=["Repaired?"], errors="ignore")
                        if not repair.empty:
                            repair_start = repair.index.min()
                            df = pd.concat([df.loc[df.index < repair_start], repair]).sort_index()
                            repaired_latest = normalized_timestamp(df.index[-1])
                            caught_up = expected_date is None or normalized_timestamp(
                                repaired_latest
                            ) >= normalized_timestamp(expected_date)
                            if (
                                "Close" in df.columns
                                and not pd.isna(df["Close"].iloc[-1])
                                and (was_incomplete or (was_lagging and caught_up))
                            ):
                                repaired_date = repaired_latest.strftime("%Y-%m-%d")
                    except Exception as repair_error:
                        print(f"  {sym} repair failed: {str(repair_error)[:80]}")
                    incomplete_latest = (
                        "Close" in df.columns and not df.empty and pd.isna(df["Close"].iloc[-1])
                    )
                    latest_date = normalized_timestamp(df.index[-1]) if not df.empty else None
                    lagging_latest = (
                        expected_date is not None
                        and latest_date is not None
                        and latest_date < normalized_timestamp(expected_date)
                    )
                incomplete_date = (
                    pd.Timestamp(cast(Any, df.index[-1])).strftime("%Y-%m-%d")
                    if incomplete_latest
                    else None
                )
                if "Close" in df.columns:
                    df = df.dropna(subset=["Close"])
                if len(df) > 100:
                    df.index = df.index.tz_localize(None)
                    if incomplete_date is not None:
                        _FAILURES.append(
                            {
                                "section": f"source yahoo:{sym}",
                                "error": (
                                    f"latest row {incomplete_date} has no close; "
                                    f"using {df.index[-1].strftime('%Y-%m-%d')}"
                                ),
                                "blocking": False,
                            }
                        )
                    if lagging_latest and expected_date is not None:
                        _FAILURES.append(
                            {
                                "section": f"source yahoo:{sym}",
                                "error": (
                                    f"latest close {df.index[-1].strftime('%Y-%m-%d')} "
                                    f"lags expected {expected_date.strftime('%Y-%m-%d')}"
                                ),
                                "blocking": False,
                            }
                        )
                    trace = f"Yahoo({len(df)} rows,{df.index[-1].strftime('%Y-%m-%d')}"
                    if repaired_date is not None:
                        trace += f",repaired={repaired_date}"
                    _SOURCE_TRACE[f"yahoo:{sym}"] = f"{trace})"
                    return df
            except Exception as e:
                print(f"  {sym} attempt {i + 1} failed: {str(e)[:80]}")
        # 指数退避:2,4,8,16 秒,给限流恢复时间
        time.sleep(2 ** (i + 1))
    raise RuntimeError(f"failed to fetch {ticker}")


def dates(idx) -> list:
    return [d.strftime("%Y-%m-%d") for d in idx]


def rnd(s, n=2) -> list:
    return [None if pd.isna(v) else round(float(v), n) for v in s]


def drawdown_episodes(close: pd.Series) -> tuple[pd.Series, list[dict[str, Any]]]:
    """Compatibility entry point for the independently tested drawdown transform."""
    return drawdown_history(close)


def weekly_last(s: pd.Series) -> pd.Series:
    """按周抽取最后一个真实 observation_date。"""
    return s.dropna().groupby(pd.Grouper(freq="W")).tail(1)


def weekly_min(s: pd.Series) -> pd.Series:
    """按周抽取最小值及其真实 observation_date。"""
    values = s.dropna()
    weeks = pd.DatetimeIndex(values.index).to_period("W-SUN")
    indices = values.groupby(weeks).idxmin()
    return values.loc[indices.tolist()]


def monthly_last(s: pd.Series, include_partial: bool = False) -> pd.Series:
    """按月抽取最后一个真实 observation_date，默认排除未结束月份。"""
    values = s.dropna()
    months = pd.DatetimeIndex(values.index).to_period("M")
    result = values.groupby(months).tail(1)
    if result.empty or include_partial:
        return result
    latest_timestamp = cast(pd.Timestamp, pd.Timestamp(cast(Any, result.index[-1])))
    latest_period_end = latest_timestamp.to_period("M").end_time.date()
    if datetime.now(UTC).date() <= latest_period_end:
        return result.iloc[:-1]
    return result


# Regime Rotation 旗舰指数（占位待用户最终确认旗舰）
# 移植自 strategy-ai/qqq/strategy.py 的 determine_state 计算逻辑（自写，只移植算法不抄源码）。
# 六状态：NORMAL / BEAR_CASH / ZONE_BATTLE_DEFEND / ZONE_BATTLE_ATTACK /
# ZONE_DESPAIR_TQQQ / TOP_ESCAPE。
# 输出每日权重、回撤、权益曲线与 20/40/60/120/250 交易日信号对账。

REGIME_WEIGHTS = {
    "NORMAL": {"qqq": 0.45, "tqqq": 0.45},
    "BEAR_CASH": {"qqq": 0.0, "tqqq": 0.0},
    "ZONE_BATTLE_DEFEND": {"qqq": 0.90, "tqqq": 0.0},
    "ZONE_BATTLE_ATTACK": {"qqq": 0.0, "tqqq": 0.99},
    "ZONE_DESPAIR_TQQQ": {"qqq": 0.0, "tqqq": 0.99},
    "TOP_ESCAPE": {"qqq": 0.90, "tqqq": 0.0},
}


def determine_state(close, ma200, ma20, drawdown, is_top_signal) -> str:
    """按 strategy-ai 默认阈值判定六种市场状态。"""
    if is_top_signal:
        return "TOP_ESCAPE"
    if ma200 is not None and close < ma200:
        if drawdown <= -0.30:
            return "ZONE_DESPAIR_TQQQ"
        elif drawdown <= -0.10:
            if ma20 is not None and close > ma20:
                return "ZONE_BATTLE_ATTACK"
            return "ZONE_BATTLE_DEFEND"
        return "BEAR_CASH"
    if drawdown < -0.10:
        return "ZONE_BATTLE_ATTACK"
    return "NORMAL"


def detect_top_signal(
    close: float,
    open_price: float,
    volume: float,
    volume_average: float,
    ath: float,
) -> bool:
    """接近历史高点时出现两倍 60 日均量的阴线。"""
    return close >= 0.95 * ath and volume > 2.0 * volume_average and close < open_price


def build_regime_rotation() -> None:
    print("== Regime Rotation（旗舰占位）")
    qqq_history = fetch_history("QQQ")[["Open", "High", "Close", "Volume"]].dropna()
    tqqq = fetch_history("TQQQ")["Close"].dropna()
    df = qqq_history.rename(
        columns={"Open": "open", "High": "high", "Close": "qqq", "Volume": "volume"}
    ).join(tqqq.rename("tqqq"), how="inner")
    close = df["qqq"]
    ma200 = close.rolling(200).mean()
    ma20 = close.rolling(20).mean()
    volume_ma60 = df["volume"].rolling(60).mean()
    ath = df["high"].cummax()
    drawdown = close / ath - 1.0

    rows = []
    for i in range(len(close)):
        if pd.isna(ma200.iloc[i]) or pd.isna(volume_ma60.iloc[i]):
            continue
        c = float(close.iloc[i])
        m2 = float(ma20.iloc[i]) if not pd.isna(ma20.iloc[i]) else None
        dd = float(drawdown.iloc[i])
        is_top = detect_top_signal(
            close=c,
            open_price=float(df["open"].iloc[i]),
            volume=float(df["volume"].iloc[i]),
            volume_average=float(volume_ma60.iloc[i]),
            ath=float(ath.iloc[i]),
        )
        state = determine_state(c, float(ma200.iloc[i]), m2, dd, is_top)
        rows.append(
            {
                "date": close.index[i].strftime("%Y-%m-%d"),
                "state": state,
                "qqq_weight": REGIME_WEIGHTS[state]["qqq"],
                "tqqq_weight": REGIME_WEIGHTS[state]["tqqq"],
                "qqq_drawdown": round(dd, 4),
            }
        )

    # 权益曲线（简化版：每日按状态权重加权 QQQ/TQQQ 收益；T+1 暂不纳入，方法论页注明差异）
    ret = df.pct_change()
    port = []
    eq = 1.0
    eq_peak = 1.0
    qqq_equity = 1.0
    for i in range(1, len(rows)):
        idx = close.index.get_indexer([pd.Timestamp(rows[i]["date"])])[0]
        w = REGIME_WEIGHTS[str(rows[i - 1]["state"])]
        daily = w["qqq"] * float(ret["qqq"].iloc[idx]) + w["tqqq"] * float(ret["tqqq"].iloc[idx])
        eq *= 1 + daily
        eq_peak = max(eq_peak, eq)
        qqq_equity *= 1 + float(ret["qqq"].iloc[idx])
        port.append(
            {
                "date": rows[i]["date"],
                "equity": round(eq, 4),
                "qqq_equity": round(qqq_equity, 4),
                "strategy_drawdown": round(eq / eq_peak - 1, 4),
            }
        )

    pin(
        "regime_rotation.json",
        {
            "dates": [r["date"] for r in rows],
            "states": [r["state"] for r in rows],
            "qqq_drawdown": [r["qqq_drawdown"] for r in rows],
            "equity_curve": port,
            "states_meta": REGIME_WEIGHTS,
            "source": "QQQ/TQQQ via Yahoo Finance；状态机参考 strategy-ai 口径",
            "return_type": "Yahoo auto-adjusted ETF returns",
            "caveat": "研究指标：未计交易成本、税费和滑点，不构成可直接交易的回测结果",
        },
    )


# ------------------------------------------------------------ RS Leaders Index（候选）
# momentum-invest/docs/04-algorithms.md §1.3：raw = 0.4*r63 + 0.2*r126 + 0.2*r189 + 0.2*r252。
# 第一版在 index 层做（SPX/NDX），避开退市股历史造成的幸存者偏差争议。


def build_rs_leaders(spx: pd.Series | None = None) -> None:
    print("== RS Leaders Index（候选）")
    if spx is None:
        spx = fetch_history("^GSPC")["Close"].dropna()
    # 简化占位：在 SPX 单序列上演示 RS 计算骨架；正式版扩到 universe。
    pin(
        "rs_leaders.json",
        {
            "dates": dates(spx.index[-300:]),
            "placeholder": True,
            "note": (
                "RS Leaders 骨架：raw = 0.4*r63 + 0.2*r126 + 0.2*r189 + 0.2*r252；universe 版待扩"
            ),
            "source": "momentum-invest/docs/04-algorithms.md §1.3",
        },
    )


# ------------------------------------------------------------ Volume Pulse / KMA breadth（候选）
# momentum-invest/docs/02-thresholds.md §5/§6：7 色 + KMA 三态。


def build_breadth_pulse() -> None:
    print("== Volume Pulse / KMA breadth（候选）")
    pin(
        "breadth_pulse.json",
        {
            "placeholder": True,
            "note": "7 色 Volume Pulse + KMA 三态 breadth 骨架；待在 QQQ/SPY 实装",
            "source": "momentum-invest/docs/02-thresholds.md §5,§6",
        },
    )


# 指数百年基础面板


def build_index_panels(prefix: str, close: pd.Series, vol_index=None, vol_name="") -> None:
    """生成长期、年度、回撤、滚动、波动率和季节性基础面板。"""
    print(f"== panels {prefix}")
    values = close.dropna().sort_index()
    month_end = monthly_last(values)
    drawdowns, episodes = drawdown_history(values)
    weekly_drawdowns = weekly_min(drawdowns).mul(100)
    payloads = {
        "century": {
            "dates": dates(values.index),
            "close": rnd(values, 2),
            "return_type": "price",
        },
        "annual": annual_performance(values),
        "drawdowns": {
            "dates": dates(weekly_drawdowns.index),
            "dd": rnd(weekly_drawdowns, 2),
            "episodes": sorted(episodes, key=lambda row: row["depth"])[:25],
            "return_type": "price",
        },
        "intrayear": intrayear_performance(values),
        "rolling5y": rolling_five_year_performance(month_end),
        "volatility": volatility_history(values, vol_index, vol_name),
        "seasonality": monthly_seasonality(month_end),
    }
    for suffix, payload in payloads.items():
        pin(f"{prefix}_{suffix}.json", payload)


def build_index_extras(prefix: str, close: pd.Series) -> None:
    """生成收益分布、持有期胜率、滚动年化、牛熊周期和极端日。"""
    print(f"== extras {prefix}")
    clean_close = close.dropna().sort_index()
    month_end = monthly_last(clean_close)
    payloads = {
        "distribution": annual_return_distribution(clean_close),
        "holding": holding_period_summary(month_end),
        "rollmatrix": rolling_cagr_payload(month_end),
        "bullbear": market_cycles(clean_close),
        "extremes": extreme_day_summary(clean_close),
    }
    for suffix, payload in payloads.items():
        pin(f"{prefix}_{suffix}.json", payload)


def build_index_suite(
    prefix: str,
    close: pd.Series,
    vol_index: pd.Series | None = None,
    vol_name: str = "",
) -> None:
    build_index_panels(prefix, close, vol_index, vol_name)
    build_index_extras(prefix, close)


def build_sp500_total_return(expected_date: pd.Timestamp) -> None:
    """保存 S&P 500 Total Return 官方指数代理，避免把价格指数当成总回报。"""
    print("== S&P 500 Total Return")
    total_return = fetch_history("^SP500TR", expected_date=expected_date)["Close"].dropna()
    pin(
        "sp500_total_return.json",
        {
            "meta": {
                "name": "S&P 500 Total Return",
                "ticker": "^SP500TR",
                "return_type": "gross total return",
                "coverage_note": "Yahoo history currently begins in 1988.",
                "source_as_of": total_return.index[-1].strftime("%Y-%m-%d"),
                "distribution": "internal research until S&P DJI data rights are licensed",
            },
            "dates": dates(total_return.index),
            "values": rnd(total_return, 4),
        },
    )
    _SOURCE_TRACE["sp500_total_return"] = "Yahoo:^SP500TR"


def merge_valuation_observation(
    existing: dict[str, Any],
    as_of: str,
    trailing_pe: float,
) -> dict[str, list[Any]]:
    """按日期合并估值快照；同日重跑会替换，不会制造重复观察。"""
    existing_dates = existing.get("dates", [])
    existing_values = existing.get("trailing_pe", [])
    if not isinstance(existing_dates, list) or not isinstance(existing_values, list):
        raise ValueError("existing valuation proxy must contain arrays")
    if len(existing_dates) != len(existing_values):
        raise ValueError("valuation proxy dates and values must have equal length")
    observations: dict[str, float] = {}
    for date, value in zip(existing_dates, existing_values, strict=True):
        if value is None:
            continue
        if not isinstance(value, int | float):
            raise ValueError("valuation proxy observations must be numeric")
        observations[str(date)] = float(value)
    observations[as_of] = round(trailing_pe, 4)
    ordered_dates = sorted(observations)
    return {
        "dates": ordered_dates,
        "trailing_pe": [observations[date] for date in ordered_dates],
    }


def build_ndx_valuation_proxy() -> None:
    """保存 QQQ trailing PE 日快照，逐日积累为 Nasdaq-100 估值代理。"""
    print("== Nasdaq-100 估值代理")
    info = yf.Ticker("QQQ").info
    trailing_pe = info.get("trailingPE")
    if not isinstance(trailing_pe, int | float) or trailing_pe <= 0:
        raise RuntimeError("QQQ trailingPE is unavailable")
    as_of = datetime.now(UTC).date().isoformat()
    path = DATA / "ndx_valuation_proxy.json"
    existing = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}
    series = merge_valuation_observation(existing, as_of, float(trailing_pe))
    pin(
        "ndx_valuation_proxy.json",
        {
            "meta": {
                "as_of": as_of,
                "proxy_ticker": "QQQ",
                "measure": "trailingPE",
                "methodology": ("Daily QQQ trailing P/E metadata retained as a valuation proxy."),
                "caveat": (
                    "This is not official Nasdaq-100 P/E and is not analyst-consensus Forward P/E."
                ),
            },
            **series,
        },
    )
    _SOURCE_TRACE["ndx_valuation_proxy"] = f"Yahoo:QQQ.info({as_of})"


def run_daily() -> None:
    print("fetching prices …")
    gspc = _fetch_close("^GSPC")
    ixic = _fetch_close("^IXIC")
    ndx = _fetch_close("^NDX")
    try:
        vix = cboe_daily_close("VIX")
        _SOURCE_TRACE["vix:primary"] = f"Cboe({len(vix)} rows,{vix.index[-1].strftime('%Y-%m-%d')})"
    except Exception as error:
        print(f"  Cboe VIX failed, falling back to Yahoo: {str(error)[:80]}")
        vix = _fetch_close("^VIX")

    run_section("Regime Rotation", build_regime_rotation)
    run_section("RS Leaders", build_rs_leaders, gspc)
    run_section("Volume Pulse", build_breadth_pulse)
    if gspc is not None:
        run_section("SP500 panels", build_index_suite, "sp500", gspc, vix, "VIX")
    if ixic is not None:
        run_section("Nasdaq panels", build_index_suite, "ixic", ixic)
    if ndx is not None:
        run_section("NDX panels", build_index_suite, "ndx", ndx)
    run_section("NDX valuation proxy", build_ndx_valuation_proxy, blocking=False)
    if gspc is not None:
        run_section("SP500 total return", build_sp500_total_return, gspc.index[-1])
    run_section("VIX 家族", build_vol_family, vix)
    run_section("宏观·利率", build_macro_rates)
    run_section("OFR 金融压力", build_financial_stress)


def run_weekly() -> None:
    run_section("美国股票配置占比", build_equity_allocation)
    run_section("CFTC COT", build_cot_vix)
    run_section("NBER 衰退期", build_recessions)
    run_section("宏观·物价", build_macro_prices)
    run_section("宏观·增长", build_macro_growth)
    run_section("成分股 Wikipedia", build_constituents)
    run_section("成分变更 Wikipedia", build_sp500_changes)
    smart_money_universe = [
        "NVDA",
        "AAPL",
        "MSFT",
        "GOOGL",
        "AMZN",
        "META",
        "TSLA",
        "JPM",
        "XOM",
        "BRK-B",
    ]
    sec_required = bool(os.environ.get("SEC_IDENTITY", "").strip())
    run_section(
        "内幕交易 Form4",
        build_insider_trades,
        smart_money_universe,
        blocking=sec_required,
    )
    run_section("13F 机构持仓", build_inst_holdings, blocking=sec_required)


def add_trace_failures() -> None:
    recorded = {failure["section"] for failure in _FAILURES}
    for source, status in _SOURCE_TRACE.items():
        section = f"source {source}"
        if status.startswith("missing") and section not in recorded:
            _FAILURES.append(
                {
                    "section": section,
                    "error": status,
                    "blocking": source not in OPTIONAL_SOURCES,
                }
            )


def load_profile_runs() -> dict[str, dict]:
    path = DATA / "meta.json"
    if not path.exists():
        return {}
    try:
        existing = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    profile_runs = existing.get("profile_runs")
    if isinstance(profile_runs, dict):
        return profile_runs
    profile = existing.get("profile")
    if not isinstance(profile, str):
        return {}
    return {
        profile: {
            "updated": existing.get("updated"),
            "source_trace": existing.get("source_trace", {}),
            "failures": existing.get("failures", []),
        }
    }


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="更新 ArcOfMarket 数据文件")
    parser.add_argument(
        "--profile",
        choices=("daily", "weekly", "full"),
        default="daily",
        help="daily 跑日频源，weekly 跑慢源，full 用于首次回填",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="任何已记录的数据源失败都返回非零退出码",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    _FAILURES.clear()
    _SOURCE_TRACE.clear()
    if args.profile in ("daily", "full"):
        run_daily()
    if args.profile in ("weekly", "full"):
        run_weekly()
    run_section("数据源目录", build_source_catalog)

    add_trace_failures()
    updated = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    profile_runs = load_profile_runs()
    profile_runs[args.profile] = {
        "updated": updated,
        "source_trace": _SOURCE_TRACE,
        "failures": _FAILURES,
    }
    source_names = "Yahoo Finance · Cboe · FRED · OFR · Wikipedia · CFTC · NBER · SEC EDGAR"
    pin(
        "meta.json",
        {
            "updated": updated,
            "profile": args.profile,
            "sources": source_names,
            "source_trace": _SOURCE_TRACE,
            "failures": _FAILURES,
            "profile_runs": profile_runs,
        },
    )
    if _FAILURES:
        print(f"\n⚠️ {len(_FAILURES)} 个小节失败：")
        for f in _FAILURES:
            severity = "阻断" if f["blocking"] else "可选"
            print(f"   · [{severity}] {f['section']}: {f['error']}")
    print("done.")
    has_blocking_failure = any(failure["blocking"] for failure in _FAILURES)
    return 1 if args.strict and has_blocking_failure else 0


def _fetch_close(ticker: str) -> pd.Series | None:
    """拉指数收盘,容错:失败留痕到 _FAILURES 返回 None,不抛。"""
    result = CallResult.invoke(fetch_history, ticker)
    if result.succeeded:
        return result.unwrap()["Close"]
    error = result.error or RuntimeError("price history failed without an error")
    message = f"{type(error).__name__}: {str(error)[:120]}"
    _FAILURES.append({"section": f"fetch {ticker}", "error": message, "blocking": True})
    print(f"  ⚠️ {ticker} 拉取失败（跳过其面板并保留上一版）: {message}")
    return None


# 外部源：Cboe VIX 家族历史数据
CBOE_HISTORY_URL = "https://cdn.cboe.com/api/global/us_indices/daily_prices/{symbol}_History.csv"

_SOURCE_TRACE: dict[str, str] = {}


def cboe_daily_close(symbol: str) -> pd.Series:
    """Load a Cboe index's published daily close history."""
    response = requests.get(
        CBOE_HISTORY_URL.format(symbol=symbol),
        headers=UA,
        timeout=30,
    )
    response.raise_for_status()
    table = pd.read_csv(StringIO(response.text))
    table.columns = [str(column).strip().upper() for column in table.columns]
    if "DATE" not in table.columns:
        raise ValueError(f"Cboe {symbol} response has no DATE column")
    value_column = "CLOSE" if "CLOSE" in table.columns else str(table.columns[-1])
    observations = table.loc[:, ["DATE", value_column]].copy()
    observations["DATE"] = pd.to_datetime(observations["DATE"], errors="coerce")
    observations[value_column] = pd.to_numeric(observations[value_column], errors="coerce")
    observations = observations.dropna().drop_duplicates("DATE", keep="last")
    if observations.empty:
        raise ValueError(f"Cboe {symbol} response contains no numeric observations")
    return observations.set_index("DATE")[value_column].sort_index()


def build_vol_family(vix_close: pd.Series | None) -> None:
    """VIX 家族日收盘进 vol_family.json。Cboe 主源(rate-limit 免疫,Sleep 0.3s 控制频率)。"""
    print("== VIX 家族（Cboe）")
    out: dict[str, list] = {}
    for name in ("VIX", "VIX9D", "VIX3M", "VIX6M", "VIX1Y", "SKEW"):
        try:
            s = cboe_daily_close(name)
            out[name] = [dates(s.index), rnd(s, 2)]
            _SOURCE_TRACE[name] = "Cboe"
        except Exception as e:
            print(f"  {name} Cboe 失败(留旧): {str(e)[:60]}")
            _SOURCE_TRACE[name] = "missing"
        time.sleep(0.3)  # 频率控制:Cboe cdn 仍客气点
    pin("vol_family.json", {k: {"dates": v[0], "close": v[1]} for k, v in out.items()})


# ------------------------------------------------------------ 外部源：FRED 官方 API
FRED_OBSERVATIONS_URL = "https://api.stlouisfed.org/fred/series/observations"


def fred_series(series_id: str, start: str = "1900-01-01") -> pd.Series:
    """Fetch one latest-vintage FRED series through the documented JSON endpoint."""
    api_key = os.environ.get("FRED_API_KEY", "").strip()
    if not api_key:
        raise RuntimeError("FRED_API_KEY is required for FRED API requests")
    parameters = {
        "api_key": api_key,
        "file_type": "json",
        "observation_start": start,
        "series_id": series_id,
        "sort_order": "asc",
    }
    last_error: Exception | None = None
    for attempt in range(3):
        try:
            response = requests.get(
                FRED_OBSERVATIONS_URL,
                params=parameters,
                headers=UA,
                timeout=60,
            )
            response.raise_for_status()
            return _fred_observations(response.json(), series_id)
        except (requests.RequestException, KeyError, TypeError, ValueError) as error:
            last_error = error
            if attempt < 2:
                time.sleep(2**attempt)
    raise RuntimeError(f"FRED {series_id} request failed") from last_error


def _fred_observations(payload: dict[str, Any], series_id: str) -> pd.Series:
    rows = payload.get("observations")
    if not isinstance(rows, list):
        raise ValueError(f"FRED {series_id} response has no observations array")
    table = pd.DataFrame.from_records(rows)
    if not {"date", "value"}.issubset(table.columns):
        raise ValueError(f"FRED {series_id} observations have an unexpected schema")
    table["date"] = pd.to_datetime(table["date"], errors="coerce")
    table["value"] = pd.to_numeric(table["value"].replace({".": None}), errors="coerce")
    table = table.dropna(subset=["date", "value"]).drop_duplicates("date", keep="last")
    if table.empty:
        raise ValueError(f"FRED {series_id} contains no numeric observations")
    return table.set_index("date")["value"].sort_index()


def _weekly(s: pd.Series, nd: int = 2) -> dict:
    w = weekly_last(s)
    return {"dates": dates(w.index), "values": rnd(w, nd)}


def percent_change_payload(
    series: pd.Series,
    precision: int = 2,
    lag: int = 12,
) -> dict:
    """Return percentage changes while treating a zero prior value as missing."""
    prior_values = series.shift(lag)
    valid_prior_values = prior_values.where(prior_values.ne(0))
    percentage_changes = series.sub(prior_values).div(valid_prior_values).mul(100).dropna()
    return {
        "dates": dates(percentage_changes.index),
        "values": rnd(percentage_changes, precision),
    }


def _period(s: pd.Series, nd: int = 1) -> dict:
    """月/季频序列保留 FRED observation_date。"""
    values = s.dropna()
    return {"dates": dates(values.index), "values": rnd(values, nd)}


def build_macro_rates() -> None:
    """资金面/利率(日频)→ macro_rates.json。每天跑。序列:SOFR/EFFR/RRP/WALCL/DGS2/10/30/T10Y2Y。"""
    print("== 宏观·利率（FRED 日频）")
    out: dict[str, dict] = {}
    plan = {
        "sofr": ("SOFR", _weekly, "percent"),
        "effr": ("EFFR", _weekly, "percent"),
        "rrp": ("RRPONTSYD", lambda s: _weekly(s, 1), "billions of US dollars"),
        "walcl": ("WALCL", lambda s: _weekly(s / 1e6, 3), "trillions of US dollars"),
        "dgs2": ("DGS2", _weekly, "percent"),
        "dgs10": ("DGS10", _weekly, "percent"),
        "dgs30": ("DGS30", _weekly, "percent"),
        "t10y2y": ("T10Y2Y", _weekly, "percentage points"),
    }
    for key, (sid, formatter, unit) in plan.items():
        try:
            out[key] = {
                **formatter(fred_series(sid)),
                "unit": unit,
                "source_series": sid,
                "frequency": "weekly sampled from source observations",
                "vintage": "latest revised; not point-in-time safe",
            }
            _SOURCE_TRACE[key] = "FRED"
        except Exception as e:
            print(f"  {sid} 失败(留旧): {str(e)[:60]}")
            _SOURCE_TRACE[key] = "missing"
        time.sleep(0.6)
    if out:
        pin("macro_rates.json", out)


def build_macro_credit() -> None:
    """信用利差(日频)→ macro_credit.json。每天跑。HY/IG OAS。"""
    print("== 宏观·信用（FRED 日频）")
    out: dict[str, dict] = {}
    for key, sid in (("hy_oas", "BAMLH0A0HYM2"), ("ig_oas", "BAMLC0A0CM")):
        try:
            out[key] = {
                **_weekly(fred_series(sid)),
                "unit": "percent",
                "source_series": sid,
                "frequency": "weekly sampled from daily close",
                "vintage": "latest revised; not point-in-time safe",
                "distribution": "internal use only; ICE license restricts third-party publication",
            }
            _SOURCE_TRACE[key] = "FRED"
        except Exception as e:
            print(f"  {sid} 失败(留旧): {str(e)[:60]}")
            _SOURCE_TRACE[key] = "missing"
        time.sleep(0.6)
    if out:
        pin("macro_credit.json", out)


OFR_FSI_URL = "https://www.financialresearch.gov/financial-stress-index/data/fsi.csv"
OFR_FSI_PAGE = "https://www.financialresearch.gov/financial-stress-index/"
OFR_FSI_FIELDS = {
    "fsi": "OFR FSI",
    "credit": "Credit",
    "equity_valuation": "Equity valuation",
    "safe_assets": "Safe assets",
    "funding": "Funding",
    "volatility": "Volatility",
    "united_states": "United States",
    "other_advanced_economies": "Other advanced economies",
    "emerging_markets": "Emerging markets",
}


def _parse_ofr_fsi(csv_text: str, today: pd.Timestamp | None = None) -> dict[str, Any]:
    """校验 OFR FSI 下载文件，并保留总指数、类别和地区贡献。"""
    frame = pd.read_csv(StringIO(csv_text))
    required = ["Date", *OFR_FSI_FIELDS.values()]
    missing = [column for column in required if column not in frame.columns]
    if missing:
        raise ValueError(f"OFR FSI missing columns: {', '.join(missing)}")

    frame = frame[required].copy()
    frame["Date"] = pd.to_datetime(frame["Date"], errors="coerce")
    for column in OFR_FSI_FIELDS.values():
        frame[column] = pd.to_numeric(frame[column], errors="coerce")
    if frame.isna().any().any():
        bad_rows = int(frame.isna().any(axis=1).sum())
        raise ValueError(f"OFR FSI contains {bad_rows} incomplete rows")
    if frame["Date"].duplicated().any():
        raise ValueError("OFR FSI contains duplicate dates")

    frame = frame.sort_values("Date")
    if len(frame) < 5_000:
        raise ValueError(f"OFR FSI coverage unexpectedly low: {len(frame)} rows")

    current_day = today if today is not None else pd.Timestamp.now(tz="UTC")
    checked_today = normalized_timestamp(current_day)
    latest = normalized_timestamp(frame["Date"].iloc[-1])
    if latest > checked_today:
        raise ValueError(f"OFR FSI latest date is in the future: {latest.date()}")
    age_days = int((checked_today - latest).days)
    if age_days > 10:
        raise ValueError(f"OFR FSI is stale by {age_days} calendar days")

    date_values = dates(pd.DatetimeIndex(frame["Date"]))
    series = {
        key: {
            "dates": date_values,
            "values": rnd(frame[column], 3),
            "unit": "index contribution",
        }
        for key, column in OFR_FSI_FIELDS.items()
    }
    latest_values = {}
    for key, column in OFR_FSI_FIELDS.items():
        latest_values[key] = round(float(frame[column].iloc[-1]), 3)
    return {
        "meta": {
            "name": "OFR Financial Stress Index",
            "coverage_start": date_values[0],
            "coverage_end": date_values[-1],
            "row_count": len(frame),
            "frequency": "daily",
            "availability_lag": "two business days",
            "vintage": "latest revised history; not point-in-time safe",
            "interpretation": "Positive values indicate above-average financial market stress.",
            "source": {
                "publisher": "Office of Financial Research",
                "page": OFR_FSI_PAGE,
                "download": OFR_FSI_URL,
            },
            "citation": (
                'Office of Financial Research, "OFR Financial Stress Index," '
                f"refreshed daily, {OFR_FSI_PAGE}"
            ),
            "disclaimer": (
                "Informational only; not investment advice. ArcOfMarket is not endorsed "
                "by the OFR or U.S. Treasury."
            ),
        },
        "series": series,
        "latest": {"date": date_values[-1], **latest_values},
    }


def build_financial_stress() -> None:
    """OFR 金融压力指数(日频，滞后两个工作日)→ financial_stress.json。"""
    print("== OFR 金融压力指数")
    response = requests.get(OFR_FSI_URL, headers=UA, timeout=60)
    response.raise_for_status()
    result = _parse_ofr_fsi(response.text)
    pin("financial_stress.json", result)
    latest = result["latest"]["date"]
    count = result["meta"]["row_count"]
    _SOURCE_TRACE["ofr_fsi"] = f"OFR({count} rows,{latest})"


def build_macro_prices() -> None:
    """物价(月频 yoy)→ macro_prices.json。每周跑够。CPI/核心PCE/PPI。"""
    print("== 宏观·物价（FRED 月频）")
    out: dict[str, dict] = {}
    for key, sid in (("cpi_yoy", "CPIAUCSL"), ("core_pce_yoy", "PCEPILFE"), ("ppi_yoy", "PPIACO")):
        try:
            out[key] = {
                **percent_change_payload(fred_series(sid)),
                "unit": "percent change from year ago",
                "frequency": "monthly",
                "source_series": sid,
                "vintage": "latest revised; not point-in-time safe",
            }
            _SOURCE_TRACE[key] = "FRED"
        except Exception as e:
            print(f"  {sid} 失败(留旧): {str(e)[:60]}")
            _SOURCE_TRACE[key] = "missing"
        time.sleep(0.6)
    if out:
        pin("macro_prices.json", out)


def build_macro_growth() -> None:
    """增长就业(月/季频)→ macro_growth.json。每周跑。UNRATE/NFP/GDP/企业利润。"""
    print("== 宏观·增长（FRED 月/季频）")
    out: dict[str, dict] = {}

    def _nfp(s: pd.Series) -> dict:
        d = s.diff().dropna()  # 千人/月
        return {"dates": dates(d.index), "values": rnd(d, 0)}

    def annualized_quarterly_growth(series: pd.Series) -> dict:
        previous_quarter = series.shift(1)
        valid_previous_quarter = previous_quarter.where(previous_quarter.gt(0))
        annualized_growth = (
            series.div(valid_previous_quarter).pow(4).mul(100).sub(100).dropna()
        )
        return {
            "dates": dates(annualized_growth.index),
            "values": rnd(annualized_growth, 1),
        }

    plan = {
        "unrate": ("UNRATE", lambda s: _period(s, 1), "percent", "monthly"),
        "nfp": ("PAYEMS", _nfp, "thousands of persons change per month", "monthly"),
        "gdp_qoq": (
            "GDPC1",
            annualized_quarterly_growth,
            "percent annualized",
            "quarterly",
        ),
        "cp_yoy": (
            "CP",
            lambda s: percent_change_payload(s, precision=1, lag=4),
            "percent change from year ago",
            "quarterly",
        ),
    }
    for key, (sid, formatter, unit, frequency) in plan.items():
        try:
            out[key] = {
                **formatter(fred_series(sid)),
                "unit": unit,
                "frequency": frequency,
                "source_series": sid,
                "vintage": "latest revised; not point-in-time safe",
            }
            _SOURCE_TRACE[key] = "FRED"
        except Exception as e:
            print(f"  {sid} 失败(留旧): {str(e)[:60]}")
            _SOURCE_TRACE[key] = "missing"
        time.sleep(0.6)
    if out:
        pin("macro_growth.json", out)


def build_macro() -> None:
    """[已弃用,保留向后兼容] 原 macro.json。新代码用 4 个分频 build_macro_*."""
    build_macro_rates()
    build_macro_credit()
    build_macro_prices()
    build_macro_growth()


def calculate_forward_pe(index_level: float, ntm_eps: float) -> float:
    """Forward PE = 当前指数点位 / 分析师未来十二个月一致预期 EPS。"""
    if index_level <= 0:
        raise ValueError("index level must be positive")
    if ntm_eps <= 0:
        raise ValueError("NTM EPS must be positive")
    return index_level / ntm_eps


def _forward_eps_input() -> dict[str, str | float] | None:
    """读取经授权的一致预期 EPS 快照；缺字段时视为不可用，绝不伪造。"""
    raw_eps = os.environ.get("SP500_FORWARD_EPS_NTM", "").strip()
    if not raw_eps:
        return None
    as_of = os.environ.get("SP500_FORWARD_EPS_AS_OF", "").strip()
    source = os.environ.get("SP500_FORWARD_EPS_SOURCE", "").strip()
    license_scope = os.environ.get("SP500_FORWARD_EPS_LICENSE_SCOPE", "internal").strip()
    if not as_of or not source:
        raise ValueError(
            "SP500_FORWARD_EPS_AS_OF and SP500_FORWARD_EPS_SOURCE are required "
            "when SP500_FORWARD_EPS_NTM is set"
        )
    as_of_date = datetime.fromisoformat(as_of).date()
    age_days = (datetime.now(UTC).date() - as_of_date).days
    if age_days < 0:
        raise ValueError("SP500_FORWARD_EPS_AS_OF cannot be in the future")
    if age_days > 45:
        raise ValueError(f"forward EPS consensus is stale by {age_days} days")
    if license_scope not in {"internal", "public"}:
        raise ValueError("SP500_FORWARD_EPS_LICENSE_SCOPE must be internal or public")
    eps = float(raw_eps)
    if eps <= 0:
        raise ValueError("SP500_FORWARD_EPS_NTM must be positive")
    return {
        "ntm_eps": eps,
        "as_of": as_of,
        "source": source,
        "license_scope": license_scope,
    }


# ------------------------------------------------------------ 外部源：Wikipedia 当前成分股
def build_constituents() -> None:
    """S&P 500 当前成分股和行业分布；不维护历史截面。"""
    print("== 成分股（Wikipedia）")
    try:
        response = requests.get(WIKIPEDIA_SP500_URL, headers=UA, timeout=30)
        response.raise_for_status()
        table = pd.read_html(StringIO(response.text))[0]
        rows = [
            {
                "ticker": r["Symbol"],
                "name": r["Security"],
                "sector": r["GICS Sector"],
                "sub": r["GICS Sub-Industry"],
                "added": str(r.get("Date added", ""))[:10],
            }
            for _, r in table.iterrows()
        ]
        sectors = pd.Series([r["sector"] for r in rows]).value_counts()
        revision = _wikipedia_revision()
        pin(
            "sp500_constituents.json",
            {
                "meta": {
                    "name": "Current S&P 500 constituent cross-section",
                    "observed_at": datetime.now(UTC).strftime("%Y-%m-%d"),
                    "caveat": "Current constituent cross-section, not historical membership.",
                    "source": {
                        "publisher": "Wikipedia contributors",
                        "page": WIKIPEDIA_SP500_URL,
                        "revision": revision,
                    },
                    "license": {
                        "id": "CC-BY-SA-4.0",
                        "url": "https://creativecommons.org/licenses/by-sa/4.0/",
                        "attribution": (
                            "Adapted from Wikipedia contributors, 'List of S&P 500 companies'."
                        ),
                        "changes_made": "Fields normalized and sector counts calculated.",
                    },
                },
                "rows": rows,
                "sectors": [{"sector": s, "count": int(c)} for s, c in sectors.items()],
            },
            license_tag=WIKIPEDIA_LICENSE_TAG,
        )
        _SOURCE_TRACE["sp500_constituents"] = f"Wikipedia(revision={revision['id']},{len(rows)})"
    except Exception as e:
        print(f"  sp500 成分股失败(留旧): {str(e)[:60]}")
        _SOURCE_TRACE["sp500_constituents"] = "missing"


WIKIPEDIA_SP500_URL = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
WIKIPEDIA_API_URL = "https://en.wikipedia.org/w/api.php"


def _optional_text(value: Any) -> str | None:
    if pd.isna(value):
        return None
    text = str(value).strip()
    return text or None


def _parse_sp500_changes_table(table: pd.DataFrame) -> list[dict[str, Any]]:
    """把 Wikipedia 多层表头转换为稳定的成分变更事件。"""
    required = {
        ("Effective Date", "Effective Date"),
        ("Added", "Ticker"),
        ("Added", "Security"),
        ("Removed", "Ticker"),
        ("Removed", "Security"),
        ("Reason", "Reason"),
    }
    if not required.issubset(set(table.columns)):
        raise ValueError("Wikipedia constituent-change table schema changed")

    changes = []
    seen = set()
    for _, row in table.iterrows():
        effective = pd.to_datetime(row[("Effective Date", "Effective Date")], errors="coerce")
        if pd.isna(effective):
            continue
        added_ticker = _optional_text(row[("Added", "Ticker")])
        removed_ticker = _optional_text(row[("Removed", "Ticker")])
        key = (effective.date().isoformat(), added_ticker, removed_ticker)
        if key in seen:
            raise ValueError(f"duplicate constituent change: {key}")
        seen.add(key)
        reason = _optional_text(row[("Reason", "Reason")])
        changes.append(
            {
                "effective_date": effective.date().isoformat(),
                "addition": {
                    "ticker": added_ticker,
                    "name": _optional_text(row[("Added", "Security")]),
                },
                "removal": {
                    "ticker": removed_ticker,
                    "name": _optional_text(row[("Removed", "Security")]),
                },
                "reason": re.sub(r"\[\d+(?:,\s*\d+)*\]", "", reason).strip() if reason else None,
            }
        )
    return sorted(changes, key=lambda item: item["effective_date"], reverse=True)


def _wikipedia_revision() -> dict[str, Any]:
    response = requests.get(
        WIKIPEDIA_API_URL,
        params={
            "action": "query",
            "prop": "revisions",
            "rvprop": "ids|timestamp",
            "titles": "List of S&P 500 companies",
            "format": "json",
        },
        headers=UA,
        timeout=30,
    )
    response.raise_for_status()
    pages = response.json()["query"]["pages"]
    page = next(iter(pages.values()))
    revision = page["revisions"][0]
    return {
        "id": int(revision["revid"]),
        "timestamp": revision["timestamp"],
        "url": (
            "https://en.wikipedia.org/w/index.php?"
            f"title=List_of_S%26P_500_companies&oldid={revision['revid']}"
        ),
    }


def build_sp500_changes() -> None:
    """独立生成 S&P 500 调入调出事实表，并保留 Wikipedia 版本归属。"""
    print("== S&P 500 成分变更（Wikipedia）")
    response = requests.get(WIKIPEDIA_SP500_URL, headers=UA, timeout=30)
    response.raise_for_status()
    tables = pd.read_html(StringIO(response.text))
    table = next(
        (
            candidate
            for candidate in tables
            if ("Added", "Ticker") in candidate.columns
            and ("Removed", "Ticker") in candidate.columns
        ),
        None,
    )
    if table is None:
        raise ValueError("Wikipedia constituent-change table not found")
    changes = _parse_sp500_changes_table(table)
    if len(changes) < 300:
        raise ValueError(f"constituent-change coverage unexpectedly low: {len(changes)}")
    revision = _wikipedia_revision()
    pin(
        "sp500_changes.json",
        {
            "meta": {
                "name": "S&P 500 constituent changes",
                "grain": "one addition/removal event per effective date",
                "count": len(changes),
                "coverage_start": changes[-1]["effective_date"],
                "coverage_end": changes[0]["effective_date"],
                "source": {
                    "publisher": "Wikipedia contributors",
                    "page": WIKIPEDIA_SP500_URL,
                    "revision": revision,
                },
                "license": {
                    "id": "CC-BY-SA-4.0",
                    "url": "https://creativecommons.org/licenses/by-sa/4.0/",
                    "attribution": (
                        "Adapted from Wikipedia contributors, 'List of S&P 500 companies'."
                    ),
                    "changes_made": "Dates and fields normalized; citation markers removed.",
                },
            },
            "changes": changes,
        },
        license_tag=WIKIPEDIA_LICENSE_TAG,
    )
    _SOURCE_TRACE["sp500_changes"] = f"Wikipedia(revision={revision['id']},{len(changes)})"


def build_source_catalog() -> None:
    """把可审查的来源登记表纳入数据哈希链并提供给前端。"""
    registry = ROOT / "config" / "source-registry.json"
    catalog = json.loads(registry.read_text(encoding="utf-8"))
    fred_registry = ROOT / "config" / "fred-series-registry.json"
    catalog["fred_series_review"] = json.loads(fred_registry.read_text(encoding="utf-8"))
    pin("source_catalog.json", catalog)


# 美国金融资产股票配置占比（FRED Z.1，需 key）
EQUITY_ALLOCATION_COMPONENTS = ("NCBEILQ027S", "FBCELLQ027S")
DEBT_ALLOCATION_COMPONENTS = (
    "BCNSDODNS",
    "CMDEBT",
    "FGSDODNS",
    "SLGSDODNS",
    "WCMITCMFODNS",
)


def build_equity_allocation() -> None:
    """生成基于 FRED Z.1 组成项的美国股票配置占比。"""
    print("== 美国金融资产股票配置占比")
    try:
        component_ids = (*EQUITY_ALLOCATION_COMPONENTS, *DEBT_ALLOCATION_COMPONENTS)
        observations = {
            series_id: fred_series(series_id, start="1945-01-01") for series_id in component_ids
        }
        share = equity_allocation_share(
            observations,
            EQUITY_ALLOCATION_COMPONENTS,
            DEBT_ALLOCATION_COMPONENTS,
        )
        payload = equity_allocation_payload(share, component_ids)
        pin("equity_allocation.json", payload)
        _SOURCE_TRACE["equity_allocation"] = "FRED"
        latest = payload["meta"]["current_value"]
        percentile = payload["meta"]["current_percentile"]
        print(f"  股票配置占比 {latest:.4f}（历史百分位 {percentile}）")
    except Exception as error:
        print(f"  股票配置占比失败（保留上一版）: {str(error)[:60]}")
        _SOURCE_TRACE["equity_allocation"] = "missing"


# ------------------------------------------------------------ CFTC COT VIX 期货持仓
COT_TFF = "https://publicreporting.cftc.gov/resource/gpe5-46if.json"
COT_VALUE_FIELDS = (
    "date",
    "lev_long",
    "lev_short",
    "lev_net",
    "am_long",
    "am_short",
    "am_net",
    "oi",
    "lev_net_pct_oi",
    "am_net_pct_oi",
)
COT_SOURCE_FIELDS = {
    "lev_long": "lev_money_positions_long",
    "lev_short": "lev_money_positions_short",
    "am_long": "asset_mgr_positions_long",
    "am_short": "asset_mgr_positions_short",
    "oi": "open_interest_all",
}


def cot_row_hash(row: dict[str, Any]) -> str:
    """Hash the CFTC values that can be revised for one report date."""
    digest = hashlib.sha256()
    for field in COT_VALUE_FIELDS:
        digest.update(field.encode())
        digest.update(b"\x00")
        digest.update(repr(row.get(field)).encode())
        digest.update(b"\x1e")
    return digest.hexdigest()


def attach_cot_observations(
    series: list[dict[str, Any]],
    existing: dict[str, Any],
    observed_at: str,
) -> tuple[list[dict[str, Any]], list[dict[str, str]]]:
    """Preserve first-seen timestamps and record later CFTC revisions."""
    previous_rows = {
        row["date"]: row
        for row in existing.get("series", [])
        if isinstance(row, dict) and isinstance(row.get("date"), str)
    }
    revisions = [row for row in existing.get("revision_history", []) if isinstance(row, dict)]
    for row in series:
        digest = cot_row_hash(row)
        previous = previous_rows.get(row["date"], {})
        previous_hash = previous.get("row_sha256")
        first_observed_at = previous.get("first_observed_at", observed_at)
        if previous_hash and previous_hash != digest:
            revisions.append(
                {
                    "report_date": row["date"],
                    "detected_at": observed_at,
                    "previous_hash": previous_hash,
                    "new_hash": digest,
                }
            )
        row.update(
            {
                "first_observed_at": first_observed_at,
                "strict_available_at": first_observed_at,
                "row_sha256": digest,
            }
        )
    return series, revisions


def fetch_cftc_vix_positions() -> list[dict[str, Any]]:
    """Fetch and normalize CFTC Traders in Financial Futures VIX rows."""
    date_field = "report_date_as_yyyy_mm_dd"
    response = requests.get(
        COT_TFF,
        params={
            "$limit": "5000",
            "$order": f"{date_field} ASC",
            "$select": ",".join((date_field, *COT_SOURCE_FIELDS.values())),
            "$where": "starts_with(market_and_exchange_names,'VIX')",
        },
        headers=UA,
        timeout=60,
    )
    response.raise_for_status()
    rows = []
    for source_row in response.json():
        try:
            normalized: dict[str, Any] = {
                name: int(source_row[source_name])
                for name, source_name in COT_SOURCE_FIELDS.items()
            }
            report_date = str(source_row[date_field])[:10]
            open_interest = normalized["oi"]
            if open_interest <= 0:
                continue
            normalized["date"] = report_date
            normalized.update(cot_availability_dates(report_date))
            normalized["lev_net"] = normalized["lev_long"] - normalized["lev_short"]
            normalized["am_net"] = normalized["am_long"] - normalized["am_short"]
            normalized["lev_net_pct_oi"] = round(
                normalized["lev_net"] / open_interest * 100,
                2,
            )
            normalized["am_net_pct_oi"] = round(
                normalized["am_net"] / open_interest * 100,
                2,
            )
            rows.append(normalized)
        except (KeyError, TypeError, ValueError):
            continue
    if not rows:
        raise RuntimeError("CFTC TFF returned no valid VIX position rows")
    return sorted(rows, key=lambda row: str(row["date"]))


def build_cot_vix() -> None:
    """Persist CFTC VIX positioning with first-seen and revision metadata."""
    print("== CFTC COT (VIX 期货站位)")
    series = fetch_cftc_vix_positions()
    observed_at = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    existing_path = DATA / "cot_vix.json"
    existing = (
        json.loads(existing_path.read_text(encoding="utf-8")) if existing_path.exists() else {}
    )
    series, revision_history = attach_cot_observations(series, existing, observed_at)
    canonical = json.dumps(series, sort_keys=True, separators=(",", ":"))
    pin(
        "cot_vix.json",
        {
            "meta": {
                "source": {
                    "publisher": "U.S. Commodity Futures Trading Commission",
                    "dataset": "Traders in Financial Futures",
                    "dataset_id": "gpe5-46if",
                    "url": COT_TFF,
                    "terms": "https://www.cftc.gov/WebPolicy/index.htm",
                },
                "units": "contracts; normalized fields are percent of open interest",
                "report_date_basis": "Tuesday positions",
                "availability_note": (
                    "CFTC normally releases Tuesday positions on Friday. The source does "
                    "not expose a per-row publication timestamp."
                ),
                "point_in_time_policy": (
                    "Strict backtests must use strict_available_at, which is the first time "
                    "ArcOfMarket actually observed the row. conservative_available_date is "
                    "an estimate for exploratory research only."
                ),
                "retrieved_at": observed_at,
                "snapshot_sha256": hashlib.sha256(canonical.encode()).hexdigest(),
            },
            "latest": series[-1],
            "revision_history": revision_history,
            "series": series,
        },
    )
    _SOURCE_TRACE["cot_vix"] = "CFTC"


def cot_availability_dates(report_date: str) -> dict[str, str]:
    """Return normal and conservative COT availability dates."""
    report = datetime.fromisoformat(report_date).date()
    return {
        "report_date": report.isoformat(),
        "normal_release_date": (report + timedelta(days=3)).isoformat(),
        "conservative_available_date": (report + timedelta(days=7)).isoformat(),
    }


# ------------------------------------------------------------ NBER 衰退期(静态历史事实,内嵌)
# NBER 官方公布。日期粒度是月份；不伪造月内具体转折日。
NBER_RECESSIONS = [
    ("1857-06", "1858-12"),
    ("1860-10", "1861-06"),
    ("1865-04", "1867-12"),
    ("1869-06", "1870-12"),
    ("1873-10", "1879-03"),
    ("1882-03", "1885-05"),
    ("1887-03", "1888-04"),
    ("1893-01", "1894-06"),
    ("1895-12", "1897-06"),
    ("1899-06", "1900-12"),
    ("1902-09", "1904-08"),
    ("1907-05", "1908-06"),
    ("1910-01", "1912-01"),
    ("1913-01", "1914-12"),
    ("1918-08", "1919-03"),
    ("1920-01", "1921-07"),
    ("1923-05", "1924-07"),
    ("1926-10", "1927-11"),
    ("1929-08", "1933-03"),
    ("1937-05", "1938-06"),
    ("1945-02", "1945-10"),
    ("1948-11", "1949-10"),
    ("1953-07", "1954-05"),
    ("1957-08", "1958-04"),
    ("1960-04", "1961-02"),
    ("1969-12", "1970-11"),
    ("1973-11", "1975-03"),
    ("1980-01", "1980-07"),
    ("1981-07", "1982-11"),
    ("1990-07", "1991-03"),
    ("2001-03", "2001-11"),
    ("2007-12", "2009-06"),
    ("2020-02", "2020-04"),
]


def nber_period(peak_month: str, trough_month: str) -> dict[str, str]:
    """Represent NBER month-level turning points without an invented mid-month day."""
    trough = cast(Any, pd.Period(trough_month, freq="M"))
    return {
        "peak_month": peak_month,
        "trough_month": trough_month,
        "chart_start": f"{peak_month}-01",
        "chart_end": trough.end_time.strftime("%Y-%m-%d"),
    }


def build_recessions() -> None:
    """NBER 衰退期 → data/recessions.json。历史定值内嵌,不联网。"""
    print("== NBER 衰退期")
    pin(
        "recessions.json",
        {
            "meta": {
                "name": "NBER 衰退期",
                "source": {
                    "publisher": "NBER Business Cycle Dating Committee",
                    "chronology_url": (
                        "https://www.nber.org/research/data/"
                        "us-business-cycle-expansions-and-contractions"
                    ),
                    "methodology_url": "https://www.nber.org/research/business-cycle-dating",
                    "citation": "Source: NBER Business Cycle Dating Committee.",
                },
                "date_resolution": "month",
                "note": (
                    "NBER identifies peaks and troughs retrospectively. chart_start and "
                    "chart_end are display boundaries derived from the published months, not "
                    "claims about an exact intramonth turning time."
                ),
            },
            "periods": [nber_period(peak, trough) for peak, trough in NBER_RECESSIONS],
        },
    )
    _SOURCE_TRACE["recessions"] = "NBER-static"


def _cf(v) -> float | None:
    try:
        return round(float(v), 2) if v is not None else None
    except (TypeError, ValueError):
        return None


# 聪明钱 ②③ SEC Form 4 + 13F（edgartools + SEC_IDENTITY）
TOP_FUNDS_13F = [
    ("Bridgewater Associates", "0001350694"),
    ("Renaissance Technologies", "0001037389"),
    ("Citadel Advisors", "0001423053"),
    ("AQR Capital Management", "0001167557"),
    ("D.E. Shaw", "0001009207"),
    ("Millennium Management", "0001273087"),
    ("Man Group", "0001637460"),
    ("Vanguard", "0000102909"),
]


def validate_sec_identity(identity: str) -> str:
    """SEC identity 是项目名加可联系邮箱，不是 API key。"""
    normalized = " ".join(identity.split())
    match = re.search(r"[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}", normalized)
    if not match:
        raise ValueError("SEC_IDENTITY must include a valid monitored email")
    domain = match.group(0).rsplit("@", 1)[1].lower()
    if domain.endswith(".local") or domain in {"example.com", "example.org", "example.net"}:
        raise ValueError("SEC_IDENTITY must not use a placeholder email domain")
    if normalized == match.group(0):
        raise ValueError("SEC_IDENTITY must include the project or company name")
    return normalized


def _load_edgar() -> Any | None:
    """加载 edgartools 并设置 SEC fair-access 身份。"""
    identity = os.environ.get("SEC_IDENTITY")
    if not identity:
        print("  缺少 SEC_IDENTITY，跳过 Form4/13F")
        return None
    try:
        import importlib

        identity = validate_sec_identity(identity)
        edgar = importlib.import_module("edgar")
        edgar.set_identity(identity)
        return edgar
    except ImportError:
        print("  edgartools 未安装，请先运行 uv sync")
        return None


def filing_metadata(filing: Any) -> dict[str, Any]:
    """Extract reproducible SEC availability and revision metadata."""
    form = str(getattr(filing, "form", "") or "")
    accepted = getattr(filing, "acceptance_datetime", None)
    accepted_at = accepted.isoformat() if hasattr(accepted, "isoformat") else None
    filing_date = str(getattr(filing, "filing_date", "") or "")[:10] or None
    return {
        "form": form,
        "filing_date": filing_date,
        "accepted_at": accepted_at,
        "available_at": accepted_at,
        "accession_number": str(getattr(filing, "accession_no", "") or "") or None,
        "is_amendment": form.endswith("/A"),
        "point_in_time_safe": accepted_at is not None,
    }


def build_insider_trades(symbols: list[str], days_back: int = 90) -> None:
    """采集 SEC Form 4 非衍生品买卖记录。"""
    print("== 内幕交易(SEC Form 4)")
    edgar = _load_edgar()
    if edgar is None:
        _SOURCE_TRACE["insider"] = "missing-sec-identity-or-edgartools"
        return
    from datetime import datetime as _dt
    from datetime import timedelta as _td

    cutoff = (_dt.now(UTC) - _td(days=days_back)).date()
    rows = []
    failed_symbols = []
    for sym in symbols:
        if sym.startswith("^"):
            continue
        try:
            company = edgar.Company(sym.upper())
            filings = company.get_filings(form="4")
            latest: Any = filings.latest(5) if hasattr(filings, "latest") else list(filings)[:5]
            if hasattr(latest, "obj"):
                latest = [latest]
            for filing in latest:
                filing_meta = filing_metadata(filing)
                try:
                    f4 = filing.obj()
                except Exception:
                    continue
                insider = getattr(f4, "insider_name", "") or ""
                if not insider:
                    continue
                nd = f4.non_derivative_table
                if not getattr(nd, "has_transactions", False):
                    continue
                txns = nd.transactions.data
                if txns.empty:
                    continue
                for _, row in txns.iterrows():
                    code = str(row.get("Code") or row.get("TransactionType") or "").upper()
                    if code not in ("P", "S", "PURCHASE", "SALE"):
                        continue
                    try:
                        txn_date = _dt.fromisoformat(str(row.get("Date", "")))
                    except ValueError:
                        continue
                    if txn_date.date() < cutoff:
                        continue
                    shares = _cf(row.get("Shares"))
                    price = _cf(row.get("Price"))
                    rows.append(
                        {
                            "ticker": sym.upper(),
                            "insider": insider,
                            "tx_type": "P" if code in ("P", "PURCHASE") else "S",
                            "tx_date": txn_date.strftime("%Y-%m-%d"),
                            "filing_date": str(filing.filing_date)[:10],
                            "accepted_at": filing_meta["accepted_at"],
                            "available_at": filing_meta["available_at"],
                            "accession_number": filing_meta["accession_number"],
                            "is_amendment": filing_meta["is_amendment"],
                            "point_in_time_safe": filing_meta["point_in_time_safe"],
                            "shares": shares,
                            "price": price,
                            "value": round(shares * price, 2) if shares and price else None,
                            "remaining": _cf(row.get("Remaining")),
                        }
                    )
        except Exception as e:
            print(f"  {sym} Form4 失败跳过: {str(e)[:50]}")
            failed_symbols.append(sym)
    if failed_symbols:
        names = ", ".join(failed_symbols)
        raise RuntimeError(f"Form4 failed for: {names}")
    pin(
        "insider_trades.json",
        {
            "meta": {
                "source": "SEC EDGAR Form 4 公开,edgartools 抓取",
                "days_back": days_back,
                "count": len(rows),
            },
            "trades": rows,
        },
    )
    _SOURCE_TRACE["insider"] = f"SEC-Form4({len(rows)})"


def build_inst_holdings() -> None:
    """SEC 13F 机构持仓(8 大顶级基金最新季)→ data/inst_holdings.json。EDGAR 公开。"""
    print("== 13F 机构持仓(SEC EDGAR)")
    edgar = _load_edgar()
    if edgar is None:
        _SOURCE_TRACE["thirteenf"] = "missing-sec-identity-or-edgartools"
        return
    from datetime import datetime as _dt

    ingested = _dt.now(UTC)
    rows = []
    failed_funds = []
    for fund_name, cik in TOP_FUNDS_13F:
        try:
            entity = edgar.Company(cik)
            filings = entity.get_filings(form=["13F-HR", "13F-HR/A"])
            if not filings:
                failed_funds.append(fund_name)
                continue
            filing = filings.latest() if hasattr(filings, "latest") else filings[0]
            filing_meta = filing_metadata(filing)
            filing_obj = filing.obj()
            report_date = str(getattr(filing_obj, "report_period", "") or "")[:10]
            report_date = report_date or ingested.strftime("%Y-%m-%d")
            holdings = filing_obj.holdings  # DataFrame: Ticker/SharesPrnAmount/Value/...
            if holdings is None or len(holdings) == 0:
                failed_funds.append(fund_name)
                continue
            for _, row in holdings.iterrows():
                ticker = row.get("Ticker") or row.get("ticker")
                if not ticker:
                    continue
                rows.append(
                    {
                        "fund": fund_name,
                        "ticker": str(ticker).upper(),
                        "report_date": report_date,
                        "filing_date": filing_meta["filing_date"],
                        "accepted_at": filing_meta["accepted_at"],
                        "available_at": filing_meta["available_at"],
                        "accession_number": filing_meta["accession_number"],
                        "form": filing_meta["form"],
                        "is_amendment": filing_meta["is_amendment"],
                        "point_in_time_safe": filing_meta["point_in_time_safe"],
                        "shares": _cf(row.get("SharesPrnAmount") or row.get("shares")),
                        "market_value": _cf(row.get("Value") or row.get("value")),
                    }
                )
        except Exception as e:
            print(f"  {fund_name} 13F 失败跳过: {str(e)[:50]}")
            failed_funds.append(fund_name)
    if failed_funds:
        names = ", ".join(failed_funds)
        raise RuntimeError(f"13F failed for: {names}")
    pin(
        "inst_holdings.json",
        {
            "meta": {
                "source": "SEC EDGAR 13F-HR 公开,edgartools",
                "count": len(rows),
                "funds": [f for f, _ in TOP_FUNDS_13F],
                "availability": (
                    "Use available_at (SEC acceptance time), not report_date, for "
                    "point-in-time analysis."
                ),
            },
            "holdings": rows,
        },
    )
    _SOURCE_TRACE["thirteenf"] = f"SEC-13F({len(rows)})"


def _hv(holding, *names):
    for name in names:
        if hasattr(holding, "get"):
            v = holding.get(name)
            if v is not None:
                return v
        v = getattr(holding, name, None)
        if v is not None:
            return v
    return None


if __name__ == "__main__":
    raise SystemExit(main())
